### ISSUE TITLE
Electron renderer add recursive

### ISSUE THREAD

**Issue by mariusdarila** [ipfs/js-ipfs-api#247]
Hello, is there any method to `add recursive a folder` from electron renderer process? Right now i get an error that recursive operation is not available in browser but electron renderer has full access(if node integration is on) to filesystem.

**Comment by diasdavid** [comment]
Hi @mariusdarila, are you performing the call on the 'browser' side of electron? To have full disk access, you can use electrons built in IPC to make a call to the Node.js process and from there call the js-ipfs-api, so that you have direct disk access.

You can find an example in Station:

- https://github.com/ipfs/station/blob/master/app/init.js#L144
- https://github.com/ipfs/station/blob/master/app/controls/drag-drop.js#L31-L64

**Comment by mariusdarila** [comment]
Same as #250 , this works ok after upgrade(electron browser and renderer).
