### ISSUE TITLE
more feedback from ipfs add

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/js-ipfs-api#567]
Currently, `addFromFs` and `ipfs add` only trigger the callback when everything is done or if an error occured. This has two problem:
- there is no feedback of the progress during the operation.
- all the stream of event of the daemon is buffered in memory and that can be expensive for a directory with a lot of files
- there is no way to process the result during the operation. You have to wait and process everything in the end.

It would be nice if there was an unbuffered version that trigger the callback for each daemon event.

**Comment by diasdavid** [comment]
Agreed. This is also related with the progress bar support - https://github.com/ipfs/js-ipfs/issues/879

In js-ipfs-api case with go-ipfs, it is really due to the nature of how the multipart message is created and how a http request is formed. We are aware that we need to level up our http-api to support things like this, see:  https://github.com/ipfs/http-api-spec/issues/116

**Comment by diasdavid** [comment]
Released on  v14.3.7 \o/
