### ISSUE TITLE
UglifyJS

### ISSUE THREAD

**Issue by povi** [ipfs/js-ipfs-api#611]
Running `npm run build` results in error:

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

./node_modules/ipfs-api/src/utils/module-config.js:7
```

when trying to build a react.js project that has ipfs-api as a dependency.

As suggested by https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify , the project should be published pre-compiled.

**Comment by atfornes** [comment]
I did some work on this, providing a prepublish routine for npm at https://github.com/atfornes/js-ipfs-api/commit/bd3a68ed814646bcb0672f29ec60356b48c8ceea.

Please, let us know if it helped

**Comment by adrianmcli** [comment]
@atfornes Can you make a PR and ask the maintainers to republish the package with the pre-compiled code?

**Comment by GoodBoy962** [comment]
@atfornes Could I simply add prepublish in node_modules/ipfs-api/package.json file?

**Comment by GoodBoy962** [comment]
@povi add `help wanted` label, please.

**Comment by atfornes** [comment]
@GoodBoy962, @adrianmcli, I am going to have a look into this today, hopefully sharing a useful pull request.

**Comment by atfornes** [comment]
@GoodBoy962 @adrianmcli, please let me know if the pull request #630 solves your issues.

**Comment by GoodBoy962** [comment]
@atfornes Thanks! Waiting for pr confirmation

**Comment by diasdavid** [comment]
Hi all!

For a time, we published all of our dependencies transpiled for a while and then we decided to revert back. The reasons where the following:

- It would increase bundle size
- There are no source maps that can bring you back to the original line of code (for when a error happens) forcing you to npm link everything when debugging
- One more step to maintain

The reality at the time was that there was no uglifyJS with ES6 support, but today (roughly started 6 months ago) there is indeed uglifyJS with ES6 support and we use it for our dist version.

You can use that version by requiring the module as `require('ipfs-api/dist/index.min.js')` and avoid hitting this problem.

What I would like to see is create-react-app to upgrade to the latest uglifyJS. Asking the entire world to publish ES5 code -- https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify -- specially when pretty much the only thing we do is Arrow Functions. Let me enphasize that there is an update uglifyJS that does indeed support ES6

**Comment by diasdavid** [comment]
Related, @hacdias hit the same issue using hjs-webpack and here is how he solved it:

- https://github.com/ipfs/webui/pull/605#issuecomment-345961216
- https://github.com/HenrikJoreteg/hjs-webpack/pull/349#pullrequestreview-78050901

**Comment by atfornes** [comment]
thanks @diasdavid,

The only issue that remains for me is that the `dist/` files are only available from official releases, and cannot be accessed from any commit/branch. This would be solved with a npm `prepare` instruction calling `aegir build`. Is there any chance that something like that would be merged?

**Comment by GoodBoy962** [comment]
@diasdavid 
Here is the next fail:  
`
Failed to minify the code from this file: 
 ./node_modules/ipfs-api/dist/index.min.js:1:33639 
`

**Comment by atfornes** [comment]
@GoodBoy962, using my pull request you could include `lib/index.js` which is transpiled, so it should not fail.

**Comment by Timer** [comment]
> Let me enphasize that there is an update uglifyJS that does indeed support ES6

Uglify may support minifying ES6, but the code will then not run in IE 9 (syntactically).
We expect support for compiling package code sometime next year, so this package will probably remain broken or require you to eject until then.

**Comment by GoodBoy962** [comment]
@atfornes which file should i change in node_modules?

**Comment by atfornes** [comment]
@GoodBoy962, I would not manually change any file in the node_modules, but instead install the modified branch with:
```npm install --save atfornes/js-ipfs-api#transpiled```

**Comment by GoodBoy962** [comment]
@atfornes I have got such a stack trace:

WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-q4spe4KTfsAS1SUHLO0wz8Qiyf1+vMIAgpRYioFYDMNqKfHQbg+AVDH3i4fvpl71/P1L0dBl+fQi+P37UYf0ew== integrity checksum failed when using sha512: wanted sha512-q4spe4KTfsAS1SUHLO0wz8Qiyf1+vMIAgpRYioFYDMNqKfHQbg+AVDH3i4fvpl71/P1L0dBl+fQi+P37UYf0ew== but got sha1-Yi4y6CSItJJ5EUpPns9F581rulU=. (6052 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-dwVUVIXsBZXwTuwnXI9RK8sBmgq09NDHzyR9SAph9eqk76gKK2JSQmZARC2zRC81JC2QTtxD0ARU5qTS25gIGw== integrity checksum failed when using sha512: wanted sha512-dwVUVIXsBZXwTuwnXI9RK8sBmgq09NDHzyR9SAph9eqk76gKK2JSQmZARC2zRC81JC2QTtxD0ARU5qTS25gIGw== but got sha1-qRlH2h9KUW6jjltOwOw3c2deCIY=. (4568 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-m+qzzcn7KUxEmd1gMbchF+Y2eIUbieUaxkWtptyHywrX0rE8QEYqPC07Vuy4Wm32/xE16NcdBctb8S0Xe/5IeQ== integrity checksum failed when using sha512: wanted sha512-m+qzzcn7KUxEmd1gMbchF+Y2eIUbieUaxkWtptyHywrX0rE8QEYqPC07Vuy4Wm32/xE16NcdBctb8S0Xe/5IeQ== but got sha1-No8lEtefnUb9/HE0mueHi7weuVw=. (25587 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-DIWtzUkw04M4k3bf1IcpS2tngXEL26YUD2M0tMDUpnUrz2hgzUBlD55a4FjdLGPvfHxS6uluGWvaVEqgBcVa+g== integrity checksum failed when using sha512: wanted sha512-DIWtzUkw04M4k3bf1IcpS2tngXEL26YUD2M0tMDUpnUrz2hgzUBlD55a4FjdLGPvfHxS6uluGWvaVEqgBcVa+g== but got sha1-PdPT55Crwk17DToDT/q6vijrvAQ=. (8471 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA== integrity checksum failed when using sha512: wanted sha512-hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA== but got sha1-4TjMdeBAxyexlm/l5fjJruJW/js=. (4655 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-c0yTD2rbQzXtSsFSVhtpvY/vS6u066PcXOX9kBB3mSO76RiUQzL340uJkGBWnlBg4/HZzqiUXtaVA7wcRcJgEw== integrity checksum failed when using sha512: wanted sha512-c0yTD2rbQzXtSsFSVhtpvY/vS6u066PcXOX9kBB3mSO76RiUQzL340uJkGBWnlBg4/HZzqiUXtaVA7wcRcJgEw== but got sha1-QKBQ7I3DtTsz2ZCUFcAsC/Gr+60=. (49753 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-ItfYfPLkWHUjckQCk8xC+LwxgK8NYcXywGigJgSwOP8Y2iyWT4f2vsZnoOXTTbo+o5yXmIUJ4gn5538SO5S3gA== integrity checksum failed when using sha512: wanted sha512-ItfYfPLkWHUjckQCk8xC+LwxgK8NYcXywGigJgSwOP8Y2iyWT4f2vsZnoOXTTbo+o5yXmIUJ4gn5538SO5S3gA== but got sha1-LN4J617jQfSEdGuwMJsyU7GxRC8=.MacBook-Pro-Alexander:MedicalCards alex$ npm install --save atfornes/js-ipfs-api#transpiled
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-q4spe4KTfsAS1SUHLO0wz8Qiyf1+vMIAgpRYioFYDMNqKfHQbg+AVDH3i4fvpl71/P1L0dBl+fQi+P37UYf0ew== integrity checksum failed when using sha512: wanted sha512-q4spe4KTfsAS1SUHLO0wz8Qiyf1+vMIAgpRYioFYDMNqKfHQbg+AVDH3i4fvpl71/P1L0dBl+fQi+P37UYf0ew== but got sha1-Yi4y6CSItJJ5EUpPns9F581rulU=. (6052 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-ItfYfPLkWHUjckQCk8xC+LwxgK8NYcXywGigJgSwOP8Y2iyWT4f2vsZnoOXTTbo+o5yXmIUJ4gn5538SO5S3gA== integrity checksum failed when using sha512: wanted sha512-ItfYfPLkWHUjckQCk8xC+LwxgK8NYcXywGigJgSwOP8Y2iyWT4f2vsZnoOXTTbo+o5yXmIUJ4gn5538SO5S3gA== but got sha1-LN4J617jQfSEdGuwMJsyU7GxRC8=. (23213 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-lreewLK/BlghmxtfH36YYVg1i8IAce4TI7oao75I1g245+6BctqTVQiBP3YUJ9C6DQOXJmkYR9X9fCLtCOJc5w== integrity checksum failed when using sha512: wanted sha512-lreewLK/BlghmxtfH36YYVg1i8IAce4TI7oao75I1g245+6BctqTVQiBP3YUJ9C6DQOXJmkYR9X9fCLtCOJc5w== but got sha1-LtgVDSShbqhlHm1u8PR8QVjOejY=. (5535 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA== integrity checksum failed when using sha512: wanted sha512-hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA== but got sha1-4TjMdeBAxyexlm/l5fjJruJW/js=. (4655 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-c0yTD2rbQzXtSsFSVhtpvY/vS6u066PcXOX9kBB3mSO76RiUQzL340uJkGBWnlBg4/HZzqiUXtaVA7wcRcJgEw== integrity checksum failed when using sha512: wanted sha512-c0yTD2rbQzXtSsFSVhtpvY/vS6u066PcXOX9kBB3mSO76RiUQzL340uJkGBWnlBg4/HZzqiUXtaVA7wcRcJgEw== but got sha1-QKBQ7I3DtTsz2ZCUFcAsC/Gr+60=. (49753 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-DIWtzUkw04M4k3bf1IcpS2tngXEL26YUD2M0tMDUpnUrz2hgzUBlD55a4FjdLGPvfHxS6uluGWvaVEqgBcVa+g== integrity checksum failed when using sha512: wanted sha512-DIWtzUkw04M4k3bf1IcpS2tngXEL26YUD2M0tMDUpnUrz2hgzUBlD55a4FjdLGPvfHxS6uluGWvaVEqgBcVa+g== but got sha1-PdPT55Crwk17DToDT/q6vijrvAQ=. (8471 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-miowhl2+U7Qle4vdLqDdPt9m09K6yZhkLDTWGoUiUzrQCn+mHHSmfJgAyGaLRZbPmTqfFFjRV1QWCW0VWUJBbQ== integrity checksum failed when using sha512: wanted sha512-miowhl2+U7Qle4vdLqDdPt9m09K6yZhkLDTWGoUiUzrQCn+mHHSmfJgAyGaLRZbPmTqfFFjRV1QWCW0VWUJBbQ== but got sha1-r02RTrBl+bXOTZ0RwcshJu7MMDg=. (28358 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-scrollbar-size@2.0.2 requires a peer of lodash@^4.17.0 but none is installed. You must install peer dependencies yourself.

npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2017-11-22T11_35_10_016Z-debug.log

**Comment by atfornes** [comment]
@GoodBoy962 please try a clean npm install, previously removing node_module folder and package-lock.json file. I have installed it with the same instruction without  problems.

this issue gives more details about those errors https://github.com/npm/npm/issues/16861

**Comment by GoodBoy962** [comment]
@atfornes thanks! That helped me to install your custom dependency.
But the build is still in fail.
`
./node_modules/ipfs-api/lib/utils/module-config.js:7 
`

**Comment by atfornes** [comment]
@GoodBoy962, can you share what is the content of that line in that file? 

In my instalation is `var multiaddr = require('multiaddr');` which should not bring errors.

can you also share what is the error message?

**Comment by GoodBoy962** [comment]
@atfornes  Here is the whole file. My 7th line is different
`
'use strict';

const getConfig = require('./default-config');
const requestAPI = require('./request-api');
const multiaddr = require('multiaddr');

module.exports = arg => {
  const config = getConfig();

  if (typeof arg === 'function') {
    return arg;
  } else if (typeof arg === 'object') {
    return requestAPI(arg);
  } else if (typeof arg === 'string') {
    const maddr = multiaddr(arg).nodeAddress();
    config.host = maddr.address;
    config.port = maddr.port;
    return requestAPI(config);
  } else {
    throw new Error('Argument must be a send function or a config object.');
  }
};
`

**Comment by atfornes** [comment]
@GoodBoy962, It is weird that a file in lib folder is not transpiled... (does not have arrow functions, for instance). 

I am sorry I cannot continue following this issue, please try again to do a clean npm install and check that babel (the transpiler that transforms original code in src/ to transpiled code in lib/) process is run.

Please let us know if you found how to fix that issue.

**Comment by GoodBoy962** [comment]
@atfornes are you sure that after installing your custom solution I should have a file which is not the same as I published here?
Which result do you have after making next steps : 1) clean npm install, 2) npm install your custom ipfs ?

**Comment by atfornes** [comment]
you are right @GoodBoy962, I missed the babel config file, which is fixed now by https://github.com/ipfs/js-ipfs-api/pull/630/commits/a1504c663c8d25c92d639b3b85a8feb7441faa9c.

Please try again now.

**Comment by GoodBoy962** [comment]
@atfornes That helped! Thank you a lot!
Unfortunately there is another the same error with cids(it is ipld) module.

**Comment by atfornes** [comment]
@GoodBoy962, you can propose a similar PR for that module then. Please let us know when it is ready.

**Comment by girards** [comment]
Hey I'm getting  `Module not found: Error: Can't resolve 'ipfs-api' in '/Users/nicolasgirardot/PleaseCom/please-web/src/components/AddListing/Place'` when trying to use your fix, I tried clean installing and all.. Hopefully you can help me fix this !

**Comment by GoodBoy962** [comment]
Any changes for that bug?

**Comment by Timer** [comment]
We now compile dependencies starting in `react-scripts@^2`, give it a try!

**Comment by KimGulmatico** [comment]
I got a simple fix on production build with `create-react-app` with 'js-ipfs/js-ipfs-api', add `<script src="https://unpkg.com/ipfs/dist/index.min.js"></script>` in index.html then you can use `const IPFS = window.Ipfs;` on `.js` file like this:

index.html

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="theme-color" content="#000000">
  
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json">
    <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">

    <title>React App</title>
	<script src="https://unpkg.com/ipfs/dist/index.min.js"></script>
  </head>
  <body>
    <noscript>
      You need to enable JavaScript to run this app.
    </noscript>
    <div id="root"></div>
    
  </body>
</html>`

App.js 

`import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

const IPFS = window.Ipfs;
const node = new IPFS();

node.on('ready', () => {
  console.log('Node ipfs is ready');
})

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default App;`

**Comment by KimGulmatico** [comment]
I got a simple fix on production build with `create-react-app` with 'js-ipfs/js-ipfs-api', add `<script src="https://unpkg.com/ipfs/dist/index.min.js"></script>` in index.html then on your javascript file declare it like this:

`const IPFS = window.Ipfs;
const node = new IPFS();

node.on('ready', () => {
  console.log('Node ipfs is ready');
})`

**Comment by fsdiogo** [comment]
Check https://github.com/ipfs/js-ipfs/issues/1321 for more info.
