### ISSUE TITLE
Cannot work with babel

### ISSUE THREAD

**Issue by cancue** [ipfs/js-ipfs-api#737]
I'm developing dapps.
I use vue-cli + truffle, and transpile codes by babel.
Our dapp can not use in ie11 browser because of ipfs-api.

Without ipfs-api, babel works perfectly.
But ipfs-api does not transpiled by babel.

I've tried a temporary solution to include ipfs-api to babel-loader option, but not work(dependency problem).
Since other node_modules written in es6 works well,
I think there is a way to solve this problem by applying it to the node_modules/ipfs-api.
But I don't know how.

What should I do?

**Comment by alanshaw** [comment]
hey @cancue, this project isn't transpiled and uses language features that the IE11 JS engine does not have. You haven't pasted any error messages so I can't help debug this issue.

The example apps for bundling with browserify and webpack might highlight any config you're missing or that is different:
https://github.com/ipfs/js-ipfs-api#in-a-web-browser-through-browserify

If you're still having problems transpiling the code then I'd recommend using a built version from one of the CDN's, and consider using https://www.npmjs.com/package/window.ipfs-fallback so that you can save on app size when your users have IPFS companion installed.

**Comment by alanshaw** [comment]
@cancue did that answer your question?

**Comment by cancue** [comment]
@alanshaw No. IE11 does not support 'const' and '() => {}' syntax.
The example and built versions on CDN still use the 'const' and '() => {}' syntax, so the way you tell me does not solve the problem.

Considering compatibility, I think this project should provide a transpiled version, or a way to transpile with babel. (currently, ipfs-api package's es6 modules are entangled, and built versions on CDN are too big to be transpiled)

**Comment by alanshaw** [comment]
Our browser targets are the latest versions of Chrome and Firefox. Unfortunately IE11 support isn't something we have the resources to devote to right now.

I'm going to close this as we can't commit to supporting it. However, if you can get the transpile working, would you be willing to send a PR to the examples to show how?
