### ISSUE TITLE
[suggestion] Usage of ES2015 features available in node@4

### ISSUE THREAD

**Issue by Dignifiedquire** [ipfs/js-ipfs-api#93]
As we already restrict the node version to be > 4 it seems very reasonable to me to start using the available ES2015 features shipping with v8 (list can be found [here](https://nodejs.org/en/docs/es6/))

This means adding two things to support it: 

1. Use babel-eslint parser for eslint instead of the standard one, as that supports all features needed.
2. Add babelify to the browserify toolchain to ensure the code still works in all browsers.

**Comment by diasdavid** [comment]
Sounds good :) can we add it as a `standard` config value instead of a gulp linting rule [(like this)](https://github.com/feross/standard#can-i-use-a-custom-js-parser-for-bleeding-edge-es6-or-es7-support)? I feel it is more explicit and we can apply this rule across every project without forcing all the other projects to use gulp.

**Comment by Dignifiedquire** [comment]
We can do that, or continue to use eslint directly, we are not forcing any project to use gulp by that, they just use the `eslint` binary directly instead of calling the `standard` binary.
