### ISSUE TITLE
Make examples tested

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/js-ipfs-api#94]
At the moment we have an examples folder but they might be outdated or broken without us knowing, so we should set up our tests to execute them to ensure they do what is expected.

**Comment by VictorBjelkholm** [comment]
Better idea, make the tests as readable as possible as use them as the examples :)

**Comment by Dignifiedquire** [comment]
I like that :)

**Comment by diasdavid** [comment]
@VictorBjelkholm what would be a good metric to define when a test is as readable as possible? Should examples be points in the README.md?

**Comment by VictorBjelkholm** [comment]
@diasdavid if you can show a new person (new to js-ipfs-api, not ipfs in general) a test case and they know what the output would be based on the assertions, the test is readable enough

**Comment by diasdavid** [comment]
@VictorBjelkholm @dignifiedquire want to give an updated comment on this one? Any hopes of getting those examples tested on CI without making the example more complicated than necessary? (Adding tests and other set ups for the tests will create noise in the learning experience)

**Comment by VictorBjelkholm** [comment]
@diasdavid yeah, not sure how we can go about to make sure the examples are working. Unit tests would add too much noise and not really be useful, since we're already testing most things + examples contains mostly glue-code to just show something...

Maybe acceptance tests or something like that could be easily setup and help? @dignifiedquire any ideas?
